# kubernetes/ingress-service.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-management-ingress
  annotations:
    # Spezifiziert die Ingress-Klasse
    kubernetes.io/ingress.class: "nginx"
    # Sagt dem Nginx-Controller, dass er Regex im Pfad verwenden soll
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: localhost
      http:
        paths:
          # Backend-Regeln:
          - path: /api(/|$)(.*)
            # pathType für Regex muss ImplementationSpecific sein
            pathType: ImplementationSpecific
            backend:
              service:
                name: core-service
                port:
                  number: 3000
          
          # WebSocket-Regel
          - path: /socket.io(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: realtime-service
                port:
                  number: 3002

          # Frontend-Regel als Catch-All
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-app
                port:
                  number: 80